apiVersion: v1
kind: Secret
metadata:
  name: additional-scrape-configs
  namespace: monitoring # Replace with your monitoring namespace
stringData:
  prometheus-additional.yaml: |
    - job_name: 'jenkins'
      metrics_path: '/prometheus'
      scheme: https
      static_configs:
        - targets:
          - 'jenkins.cave-jarvis.com' # e.g., jenkins.example.com:8080

    - job_name: 'kube-state-metrics'
      static_configs:
        - targets: ['stable-kube-state-metrics.monitoring.svc.cluster.local:8080'] # Adjust if necessary
      metric_relabel_configs:
        - source_labels: [__address__]
          target_label: __address__
          regex: (.*):.*
          replacement: ${1}:8080

    - job_name: 'metrics-server'
      scheme: https
      tls_config:
        insecure_skip_verify: true
      static_configs:
      - targets: ['metrics-server.kube-system.svc.cluster.local:443']

    - job_name: 'flask-app1'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - flask-app
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: flask-app1
        action: keep
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: job
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod

    - job_name: 'inventory-app'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - flask-app
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: inventory-app
        action: keep
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: job
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod

    - job_name: 'order-app'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - flask-app
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: order-app
        action: keep
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: job
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod

    - job_name: 'user-app'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - flask-app
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: user-app
        action: keep
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: ${1}:${2}
        target_label: __address__
      - source_labels: [__meta_kubernetes_pod_label_app]
        target_label: job
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod