apiVersion: v1
kind: Secret
metadata:
  name: jenkins-scrape-config
  namespace: monitoring
stringData:
  jenkins-scrape.yaml: |
    - job_name: 'jenkins'
      metrics_path: '/prometheus'
      scheme: https
      static_configs:
        - targets:
          - 'jenkins.cave-jarvis.com'