apiVersion: v1
kind: Service
metadata:
  name: flask-app1-service
  namespace: flask-app
spec:
  selector:
    app: flask-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ssl-redirect
  namespace: flask-app
  annotations:
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  type: NodePort
  ports:
    - name: use-annotation
      port: 80
      targetPort: use-annotation