apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      containers:
      - name: user-app
        image: public.ecr.aws/o0y6x7h1/sampleapp/user-app:latest # Placeholder
        ports:
        - containerPort: 5002
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_HOST
          value: my-app.cly48wisg5ac.eu-central-1.rds.amazonaws.com 
        - name: DB_PORT
          value: "3306"  # Default MySQL port
        - name: DB_NAME
          value: appdb # Your database name
        - name: DB_USER
          value: admin # Your database username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret # The name of the Secret with DB credentials
              key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: user-app
  namespace: flask-app
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
  type: ClusterIP